eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://serviceregistry:8761/eureka

okta:
  oauth2:
    issuer: https://dev-31306720.okta.com/oauth2/default
    audience: api://default
